# Generated by Django 6.1 on 2026-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('NNI', models.CharField(max_length=100)),
                ('nb_telephone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type_user', models.CharField(choices=[('client', 'Client'), ('agence', 'Agence'), ('admin', 'Admin')], default='client', max_length=10)),
            ],
        ),
    ]
