# Generated by Django 6.1 on 2026-09-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nb_telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
