# Generated by Django 6.1 on 2026-09-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_trans', models.DateTimeField(auto_now_add=True)),
                ('type_trans', models.CharField(choices=[('envoi', 'Envoi'), ('retrait', 'Retrait'), ('depot', 'Depot'), ('reception', 'Réception')], max_length=10)),
                ('statut_trans', models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('annulé', 'Annulé')], default='en attente', max_length=15)),
                ('deposent', models.ForeignKey(db_column='deposent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_deposit', to='wallet.wallet')),
                ('wallet_destinataire', models.ForeignKey(db_column='wallet_destinataire_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_destinataire', to='wallet.wallet')),
                ('wallet_expediteur', models.ForeignKey(db_column='wallet_expediteur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_expediteur', to='wallet.wallet')),
            ],
        ),
    ]
