# Generated by Django 6.1 on 2026-09-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('depot', 'Depot'), ('reception', 'Réception')], max_length=10),
        ),
    ]
