# Generated by Django 6.1 on 2026-09-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type_trans'),
        ('wallet', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_trans']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposent',
            field=models.ForeignKey(blank=True, db_column='deposent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_deposit', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('depot', 'Depot'), ('retrait', 'Retrait')], max_length=10),
        ),
    ]
